# docker compose for grafana and influxdb
# https://grafana.com/docs/grafana/latest/installation/docker/
version: '2'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086 # port pour accéder à influxdb
      - 8083:8083 # port pour accéder à l'interface web de influxdb
    volumes: # endroit sur le disque pour mémoire permanente, pour garder le travail deja fait
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secret
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXCB_INIT_BUCKET=mybucket
      - INFLUXDB_ADMIN_ENABLED=true
#  grafana:
    # image: grafana/grafana:7.3.6
    # container_name: grafana
    # restart: always
    # ports:
    #   - 3000:3000
    # volumes:
    #   - ./grafana:/var/lib/grafana
    # environment:
    #   - GF_SECURITY_ADMIN_USER=admin
    #   - GF_SECURITY_ADMIN_PASSWORD=secret
    #   - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
#volumes:
#  influxdb: ./influxdb
#  grafana: ./grafana